shiro:
  realm: com.iyihua.itimes.config.security.MyRealm
  loginUrl: /view/sign-in.html
  successUrl: /item.html
  unauthorizedUrl: /forbidden.html
  filterChainDefinitions:
    "/login": anon
    "/view/sign-in": anon
    "/view/**": anon
    "/static/**": anon
    "/auth": anon
    "/logout": logout
    "/**": authc